const std = @import("std");
const sh = @import("shared.zig");
const Allocator = std.mem.Allocator;

fn typescriptTypeName(gpa: Allocator, comptime T: type) []const u8 {
    var w = std.Io.Writer.Allocating.init(gpa);
    switch (@typeInfo(T)) {
        .int => {
            return "int";
        },
        .float => {
            return "number";
        },
        .bool => {
            return "boolean";
        },
        .array => |array| {
            const elem = typescriptTypeName(gpa, array.child);
            var buffer = std.ArrayList(u8).initCapacity(gpa, 100) catch unreachable;
            for (0..array.len) |_| {
                buffer.appendSlice(gpa, elem) catch unreachable;
                buffer.appendSlice(gpa, ", ") catch unreachable;
            }
            w.writer.print("[{s}]", .{buffer.items}) catch unreachable;
            return w.written();
        },
        .pointer => |ptr| {
            if (ptr.size == .slice) {
                // special case for strings
                if (ptr.is_const and ptr.child == u8) {
                    return "string";
                }
                w.writer.print("{s}[]", .{typescriptTypeName(gpa, ptr.child)}) catch unreachable;
                return w.written();
            }
        },
        .optional => |opt| {
            w.writer.print("({s} | null)", .{typescriptTypeName(gpa, opt.child)}) catch unreachable;
            return w.written();
        },
        else => {
            // return "any";
            const name = @typeName(T);
            // remove prefix
            return std.mem.trimStart(u8, name, "shared.");
        },
    }
}

fn generateStruct(gpa: Allocator, comptime T: type, generated: *std.StringHashMap(void), dst: *std.Io.Writer) !void {
    var childBuffer = std.Io.Writer.Allocating.init(gpa);

    try dst.print("export type {s} = {{\n", .{typescriptTypeName(gpa, T)});
    inline for (@typeInfo(T).@"struct".fields) |value| {
        try dst.print("\t{s}: {s};\n", .{ value.name, typescriptTypeName(gpa, value.type) });
        // recurse
        try generateType(gpa, value.type, generated, &childBuffer.writer);
    }
    try dst.print("}}\n\n", .{});

    // copy children
    try dst.writeAll(childBuffer.written());
}

fn generateType(gpa: Allocator, comptime T: type, generated: *std.StringHashMap(void), dst: *std.Io.Writer) !void {
    const name = typescriptTypeName(gpa, T);
    if (generated.get(name) != null) {
        return;
    }
    try generated.put(name, undefined);
    switch (@typeInfo(T)) {
        .int => {
            try dst.print("type int = number;\n\n", .{});
        },
        .@"struct" => {
            try generateStruct(gpa, T, generated, dst);
        },
        .array => |array| {
            try generateType(gpa, array.child, generated, dst);
        },
        .pointer => |ptr| {
            if (ptr.size == .slice) {
                try generateType(gpa, ptr.child, generated, dst);
            }
        },
        .optional => |opt| {
            try generateType(gpa, opt.child, generated, dst);
        },
        else => {},
    }
}

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    const gpa = arena.allocator();
    defer arena.deinit();

    // avoid duplications
    var generated = std.StringHashMap(void).init(gpa);

    var dst = std.Io.Writer.Allocating.init(gpa);

    try dst.writer.print("// Code generated by bindings.zig. DO NOT EDIT.\n", .{});

    try generateType(gpa, sh.ChildrenPlanning, &generated, &dst.writer);
    try generateType(gpa, sh.WeekPros, &generated, &dst.writer);
    try generateType(gpa, sh.Roulements, &generated, &dst.writer);

    try std.fs.cwd().writeFile(.{ .sub_path = "../src/logic/types.ts", .data = dst.written() });

    std.debug.print("Done.\n", .{});
}
