// Code generated by bindings.zig. DO NOT EDIT.
export type CheckIn = {
  children: ChildrenPlanning;
  pros: ProsPlanning;
  roulements: Roulements | null;
};

export type ChildrenPlanning = {
  firstMonday: Date;
  children: ChildCreneaux[];
  weekCount: int;
};

type int = number;

export type ChildCreneaux = {
  child: Child;
  creneaux: [
    ChildDay | null,
    ChildDay | null,
    ChildDay | null,
    ChildDay | null,
    ChildDay | null
  ][];
};

export type Child = {
  nom: string;
  dateNaissance: string;
  isMarcheur: boolean;
};

export type ChildDay = {
  horaires: Range;
  isAdaptation: boolean;
};

export type Range = {
  start: Horaire;
  end: Horaire;
};

export type Horaire = {
  heure: int;
  minute: int;
};

export type ProsPlanning = {
  firstMonday: Date;
  weeks: WeekPros[];
};

export type WeekPros = {
  week: int;
  prosHoraires: WeekPro[];
  roulement: int;
  reunion: Reunion | null;
};

export type WeekPro = {
  pro: Pro;
  horaires: [
    HoraireTravail,
    HoraireTravail,
    HoraireTravail,
    HoraireTravail,
    HoraireTravail
  ];
  detachement: Detachement | null;
};

export type Pro = {
  prenom: string;
  color: string;
  isInterimaire: boolean;
};

export type HoraireTravail = {
  presence: Range;
  pause: Range;
};

export type Detachement = {
  dayIndex: int;
  horaires: Range;
};

export type Reunion = {
  day: int;
  horaire: Horaire;
};

export type Roulements = {
  weeks: [
    [Creneau, Creneau, Creneau, Creneau],
    [Creneau, Creneau, Creneau, Creneau],
    [Creneau, Creneau, Creneau, Creneau],
    [Creneau, Creneau, Creneau, Creneau],
    [Creneau, Creneau, Creneau, Creneau]
  ][];
};

export type Creneau = "o" | "m" | "s" | "f";

export type Diagnostic = {
  dayIndex: DayIndex;
  horaireIndex: int;
  horaire: Horaire;
  message: Diagnostic_Message;
};

export type DayIndex = {
  week: int;
  day: int;
};

export type Diagnostic_Message = {
  title: string;
  message: string;
};

export type CreateIn = {
  children: ChildrenPlanning;
  roulements: RoulementsAndPros;
  firstWeekRoulement: int;
};

export type RoulementsAndPros = {
  pros: [Pro, Pro, Pro, Pro];
  roulements: Roulements;
};

export type CreateOut = { done: ProsPlanning } | { err: string };
