// Code generated by bindings.zig. DO NOT EDIT.
export type ChildrenPlanning = {
	children: ChildCreneaux[];
	weekCount: int;
}

export type ChildCreneaux = {
	child: Child;
	creneaux: [(ChildDay | null), (ChildDay | null), (ChildDay | null), (ChildDay | null), (ChildDay | null), ][];
}

export type Child = {
	nom: string;
	dateNaissance: string;
	isMarcheur: boolean;
}

type int = number;

export type ChildDay = {
	horaires: Range;
	isAdaptation: boolean;
}

export type Range = {
	start: Horaire;
	end: Horaire;
}

export type Horaire = {
	heure: int;
	minute: int;
}

export type WeekPros = {
	week: int;
	prosHoraires: WeekPro[];
	roulement: int;
	reunion: (Reunion | null);
}

export type WeekPro = {
	pro: Pro;
	horaires: [HoraireTravail, HoraireTravail, HoraireTravail, HoraireTravail, HoraireTravail, ];
	detachement: (Detachement | null);
}

export type Pro = {
	prenom: string;
	color: string;
	isInterimaire: boolean;
}

export type HoraireTravail = {
	presence: Range;
	pause: Range;
}

export type Detachement = {
	dayIndex: int;
	horaires: Range;
}

export type Reunion = {
	day: int;
	horaire: Horaire;
}

